version: '3'

services:
  geolocation-api:
    container_name: geolocation-api
    build: .
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    networks:
      - geolocation-api-network
    depends_on:
      - geolocation-mongodb

  geolocation-mongodb:
    container_name: geolocation-mongodb
    image: mongo:3
    ports:
      - "27017:27017"
    volumes:
      - ./mongodbData:/data/db
    networks:
      - geolocation-api-network

  geolocation-redis:
    image: redis:6-alpine
    container_name: geolocation-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redisData:/data
    networks:
      - geolocation-api-network

networks:
  geolocation-api-network:
    driver: bridge
